# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home Page"
url = "https://nafaal.com"
weight = 1

[main.params]
icon = "home"
newtab = false

[[social]]
identifier = "x"
name = "X"
url = "https://x.com"
weight = 2

[social.params]
icon = "twitter-x-logo"

[[social]]
identifier = "linkedin"
name = "Linkedin"
url = "https://linkedin.com"
weight = 3

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/CaiJimmy/hugo-theme-stack"
weight = 4

[social.params]
icon = "brand-github"


